language: node_js
node_js:
  - '6'

notifications:
  email: false

cache:
  directories:
    - node_modules

before_script: npm prune

script:
  - npm run precommit

after_success:
  - "./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls"
